### ISSUE TITLE
ARC compatibility

### ISSUE THREAD

**Issue by rabovik** [nevyn/SPSuccinct#2]
I want to use this lib in my ARC project.
I added `-fobjc-arc` to all .m files and changed `__block` modifier in `$depends` macros to avoid retain cycles:

```objective-c
#define $depends(associationName, object, keypath, ...) ({ \
	__block __unsafe_unretained __typeof(self) selff = self  /* Weak reference*/ \
	SPAddDependencyV(self, associationName, object, keypath, __VA_ARGS__, nil);\
})
```
But got a compile error `The type 'typeof (self)' aka 'MyObject *const __strong' already has retainment attributes set on it`
So I changed the macros to:

```objective-c
#define $depends(associationName, object, keypath, ...) ({ \
	__block __unsafe_unretained id selff = self; /* Weak reference*/ \
	SPAddDependencyV(self, associationName, object, keypath, __VA_ARGS__, nil);\
})
```
But now I have to explicitly cast `selff` to `(MyObject *)` inside the block.

Is there a better solution to write macros and to avoid casting?

Are there any other changes I should make to get this awesome lib work properly under ARC?

**Comment by nevyn** [comment]
Wowwww, Mar 29, 2012. That's over three years ago. @rabovik, my deepest apologies. I must've been deep in some release crunch back then.

Since you posted your issue, some kind soul has added:
```objective-c
#if __has_feature(objc_arc)
#define SPDependsWeakSelf __weak __typeof(self)
#else
#define SPDependsWeakSelf __block __typeof(self)
#endif
```

which ensures that the headers are all ARC safe. The implementation decidedly requires MRC though, due to all the dark magic voodoo going on. I started cleaning it up but quickly gave up.

I hope that you worked it out, back then three years ago; if you still want the lib and are having trouble, please ping me again. And thank you for thinking that my lib is awesome :heart::heart::heart:
